// ============================================================
// Night Vibe Checker — Demo Venue Fallback Data
//
// Used when the Google Places API is unavailable (REQUEST_DENIED,
// quota exceeded, or key not configured).
//
// These are demo venues that give the app a populated home feed
// for demos even when the live API is broken.
// ============================================================

import type { VenueBasic, VenueDetail } from "@/types";

export const DEMO_VENUES: VenueBasic[] = [
  {
    placeId: "ChIJN1t_tDeuEmsRUsoyG83frY4",
    name: "The Neon Lounge",
    address: "42 Neon Street, New York, NY 10001",
    lat: 40.7484,
    lng: -73.9967,
    type: "night_club",
    googleRating: 4.5,
    totalRatings: 1284,
    priceLevel: 3,
    cachedVibeScore: undefined,
  },
  {
    placeId: "ChIJp0wCs1lYwokRvB65x0xnGrA",
    name: "Electric Garden Bar",
    address: "88 Grove Ave, Brooklyn, NY 11211",
    lat: 40.7145,
    lng: -73.9619,
    type: "bar",
    googleRating: 4.3,
    totalRatings: 876,
    priceLevel: 2,
    cachedVibeScore: undefined,
  },
  {
    placeId: "ChIJAQAAyANawokRQdbiHBn56AA",
    name: "Velvet Underground Club",
    address: "15 W 26th St, New York, NY 10010",
    lat: 40.7446,
    lng: -73.9903,
    type: "night_club",
    googleRating: 4.6,
    totalRatings: 2103,
    priceLevel: 3,
    cachedVibeScore: undefined,
  },
  {
    placeId: "ChIJMSGKoWtZwokRulVqzQFZZMQ",
    name: "Midnight Rooftop Lounge",
    address: "230 5th Ave, New York, NY 10001",
    lat: 40.7448,
    lng: -73.9878,
    type: "bar",
    googleRating: 4.4,
    totalRatings: 3421,
    priceLevel: 3,
    cachedVibeScore: undefined,
  },
  {
    placeId: "ChIJZeH1eyl344kRA4JmJbU2aAk",
    name: "Pulse Dance Club",
    address: "685 Washington St, New York, NY 10014",
    lat: 40.7326,
    lng: -74.0065,
    type: "night_club",
    googleRating: 4.2,
    totalRatings: 1567,
    priceLevel: 4,
    cachedVibeScore: undefined,
  },
  {
    placeId: "ChIJ3SPdse38woAR1CBbD_45Eaw",
    name: "The Golden Hour",
    address: "17 Little W 12th St, New York, NY 10014",
    lat: 40.7392,
    lng: -74.0089,
    type: "bar",
    googleRating: 4.7,
    totalRatings: 2890,
    priceLevel: 2,
    cachedVibeScore: undefined,
  },
];

/** Map from placeId to full VenueDetail for demo venues */
export const DEMO_VENUE_DETAILS: Record<string, VenueDetail> = {
  "ChIJN1t_tDeuEmsRUsoyG83frY4": {
    placeId: "ChIJN1t_tDeuEmsRUsoyG83frY4",
    name: "The Neon Lounge",
    address: "42 Neon Street, New York, NY 10001",
    lat: 40.7484,
    lng: -73.9967,
    type: "night_club",
    googleRating: 4.5,
    totalRatings: 1284,
    priceLevel: 3,
    phoneNumber: "+1 212-555-0101",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: Closed",
      "Tuesday: Closed",
      "Wednesday: 9:00 PM – 4:00 AM",
      "Thursday: 9:00 PM – 4:00 AM",
      "Friday: 9:00 PM – 5:00 AM",
      "Saturday: 9:00 PM – 5:00 AM",
      "Sunday: 9:00 PM – 3:00 AM",
    ],
    editorialSummary:
      "An iconic NYC club known for its neon-drenched interiors and electric atmosphere.",
    photos: [],
    reviews: [
      "Best nightclub in the city — the DJ sets are incredible and the crowd is amazing.",
      "Went last Friday and had a great time. Drinks are pricey but worth it.",
      "The rooftop area opens at midnight and the views are stunning.",
    ],
  },
  "ChIJp0wCs1lYwokRvB65x0xnGrA": {
    placeId: "ChIJp0wCs1lYwokRvB65x0xnGrA",
    name: "Electric Garden Bar",
    address: "88 Grove Ave, Brooklyn, NY 11211",
    lat: 40.7145,
    lng: -73.9619,
    type: "bar",
    googleRating: 4.3,
    totalRatings: 876,
    priceLevel: 2,
    phoneNumber: "+1 718-555-0188",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: 5:00 PM – 2:00 AM",
      "Tuesday: 5:00 PM – 2:00 AM",
      "Wednesday: 5:00 PM – 2:00 AM",
      "Thursday: 5:00 PM – 3:00 AM",
      "Friday: 4:00 PM – 4:00 AM",
      "Saturday: 2:00 PM – 4:00 AM",
      "Sunday: 2:00 PM – 12:00 AM",
    ],
    editorialSummary:
      "A lush outdoor garden bar in the heart of Williamsburg with craft cocktails and live DJs.",
    photos: [],
    reviews: [
      "Love this place — the outdoor garden is so beautiful and the cocktails are creative.",
      "Great vibes on weekends. The Thursday DJ nights are a highlight.",
      "Hidden gem in Brooklyn. Locals know, tourists haven't found it yet.",
    ],
  },
  "ChIJAQAAyANawokRQdbiHBn56AA": {
    placeId: "ChIJAQAAyANawokRQdbiHBn56AA",
    name: "Velvet Underground Club",
    address: "15 W 26th St, New York, NY 10010",
    lat: 40.7446,
    lng: -73.9903,
    type: "night_club",
    googleRating: 4.6,
    totalRatings: 2103,
    priceLevel: 3,
    phoneNumber: "+1 212-555-0126",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: Closed",
      "Tuesday: Closed",
      "Wednesday: Closed",
      "Thursday: 10:00 PM – 4:00 AM",
      "Friday: 10:00 PM – 5:00 AM",
      "Saturday: 10:00 PM – 5:00 AM",
      "Sunday: Closed",
    ],
    editorialSummary:
      "Upscale nightclub experience with world-class DJs and a sophisticated crowd.",
    photos: [],
    reviews: [
      "This place has the best sound system in NYC. The bass hits perfect.",
      "Exclusive but worth it. Make a reservation in advance.",
      "Incredible light show on Saturday nights. The crowd is amazing.",
    ],
  },
  "ChIJMSGKoWtZwokRulVqzQFZZMQ": {
    placeId: "ChIJMSGKoWtZwokRulVqzQFZZMQ",
    name: "Midnight Rooftop Lounge",
    address: "230 5th Ave, New York, NY 10001",
    lat: 40.7448,
    lng: -73.9878,
    type: "bar",
    googleRating: 4.4,
    totalRatings: 3421,
    priceLevel: 3,
    phoneNumber: "+1 212-555-0230",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: 5:00 PM – 1:00 AM",
      "Tuesday: 5:00 PM – 1:00 AM",
      "Wednesday: 5:00 PM – 2:00 AM",
      "Thursday: 5:00 PM – 3:00 AM",
      "Friday: 4:00 PM – 4:00 AM",
      "Saturday: 12:00 PM – 4:00 AM",
      "Sunday: 12:00 PM – 10:00 PM",
    ],
    editorialSummary:
      "Stunning 360-degree views from the top of the Flatiron District with craft cocktails.",
    photos: [],
    reviews: [
      "Best rooftop in Manhattan. The Empire State Building view at night is breathtaking.",
      "Come early to get a spot by the railing. Views are incredible.",
      "Pricey drinks but the atmosphere makes up for it. Perfect for dates.",
    ],
  },
  "ChIJZeH1eyl344kRA4JmJbU2aAk": {
    placeId: "ChIJZeH1eyl344kRA4JmJbU2aAk",
    name: "Pulse Dance Club",
    address: "685 Washington St, New York, NY 10014",
    lat: 40.7326,
    lng: -74.0065,
    type: "night_club",
    googleRating: 4.2,
    totalRatings: 1567,
    priceLevel: 4,
    phoneNumber: "+1 212-555-0685",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: Closed",
      "Tuesday: Closed",
      "Wednesday: Closed",
      "Thursday: Closed",
      "Friday: 11:00 PM – 6:00 AM",
      "Saturday: 11:00 PM – 6:00 AM",
      "Sunday: Closed",
    ],
    editorialSummary:
      "Legendary Meatpacking District dance club with international DJ bookings.",
    photos: [],
    reviews: [
      "This club brings in the best DJs in the world. Worth every penny.",
      "Three floors of music — you'll find your vibe wherever you land.",
      "The Friday late-night sets go until 6am. Absolute banger every week.",
    ],
  },
  "ChIJ3SPdse38woAR1CBbD_45Eaw": {
    placeId: "ChIJ3SPdse38woAR1CBbD_45Eaw",
    name: "The Golden Hour",
    address: "17 Little W 12th St, New York, NY 10014",
    lat: 40.7392,
    lng: -74.0089,
    type: "bar",
    googleRating: 4.7,
    totalRatings: 2890,
    priceLevel: 2,
    phoneNumber: "+1 212-555-0017",
    website: "https://night-vibe-checker.vercel.app",
    openingHours: [
      "Monday: 4:00 PM – 1:00 AM",
      "Tuesday: 4:00 PM – 1:00 AM",
      "Wednesday: 4:00 PM – 2:00 AM",
      "Thursday: 4:00 PM – 3:00 AM",
      "Friday: 3:00 PM – 4:00 AM",
      "Saturday: 1:00 PM – 4:00 AM",
      "Sunday: 1:00 PM – 11:00 PM",
    ],
    editorialSummary:
      "A beloved neighborhood bar in the West Village with natural wine and perfect vibes.",
    photos: [],
    reviews: [
      "My absolute favorite bar in NYC. The natural wine list is outstanding.",
      "Cozy and intimate but never pretentious. Staff knows everyone by name.",
      "The golden hour specials (4-6pm) are the best deal in the city.",
    ],
  },
};

/** Returns true if the given place ID is one of the demo venues */
export function isDemoVenue(placeId: string): boolean {
  return placeId in DEMO_VENUE_DETAILS;
}
